### ISSUE TITLE
Synchronizing stopped working after NC update

### ISSUE THREAD

**Issue by jgibbon** [Huessenbergnetz/libfuoten#66]
Hi,
at first I thought it might've been #65, ~~but I think the root cause could be https://github.com/nextcloud/news/issues/935~~

~~The following items have been removed in News 16.0.0:~~

> ## API
> * `/api/v1-2/user`
> * `/api/v1-2/user/avatar`
> 
> ## CLI
> * `news:updater:all-feeds`

cheers

**Comment by buschmann23** [comment]
But that change is planned for Nextcloud News 16.0.0 only - and that version is not released yet. Or are you using the current git master?

Do you get any error message from Fuoten when synchronization fails?

**Comment by jgibbon** [comment]
You're right, I must have jumped to the wrong conclusions.

News version on server is 15.1.1
The error, which is also shown on the bottom of Fuoten, is

> [C] 19:24:33:677: ServerError: Internal server error — An unexpected condition was encountered on the server.
> [C] 19:24:33:678: ServerError: Internal server error — An unexpected condition was encountered on the server.

It is shown right after "Requesting updated and new articles".

I did have to update the client on my android device, as well, though.

**Comment by buschmann23** [comment]
The log says that the error happened on the server side. So you should have a look into your server logs.

**Comment by jgibbon** [comment]
You are right, it turns out to be
`AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 145'
`.
Funnily enough, the android client just seems to ignore that and still show new entries. Also, I wasn't able to fix it by giving it even more memory.

I was then able to work around the issue by deleting the Fuoten configuration and logging in again. (I also marked most feeds as read in the web ui, which I rarely did in the past.)

Sorry for wasting your time, I should have thought about all that before. Thanks for your help! :)

**Comment by buschmann23** [comment]
No, you have not wasted my time. :) I had the same issue on the server side. I raised the memory limits for my Nextcloud instance and then ran into issue #67.

I am not sure what the Android client does differently when updating news items. Maybe not using compression? I do not know…

But even disabling compression would not help against issue #67, that would need updated Qt on SailfishOS. :(

**Comment by jgibbon** [comment]
The android client did generate a server error, as well, even with >1gb of memory, but still continued to show new items as far as I could tell.

**Comment by buschmann23** [comment]
Thanks for the info. Than it is really bad for SFOS, because #67 needs newer Qt. At least that issue was not very common until now, I personally had it only once and resolved it the same way as you by cleaning up Fuoten and reauthenticate it. I was wondering a bit that it never happened before, because I already had massive syncs in the past without this error - maybe they have never been that huge. Looking in local debug build output, the failing sync had a size of nearly 120MiB of JSON data - too much for QJsonDocument.
