### ISSUE TITLE
Port Q_DISABLE_MOVE to Q_DISABLE_COPY_MOVE

### ISSUE THREAD

**Issue by dangelog** [Huessenbergnetz/libfuoten#70]
Hi,

I'm doing a bit of a research on usages of `Q_DISABLE_MOVE` in the open source codebases. libfuoten and fuoten feature a few of these.

I am in the process to deprecate and/or remove that macro from Qt, as it's error prone. Its only valid use case is in combination with `Q_DISABLE_COPY`, but if one needs both, then there's `Q_DISABLE_COPY_MOVE` as a direct replacement. Instead, using `Q_DISABLE_MOVE` _alone_ is almost certainly a mistake. 

For this reason I'd like to stop supporting it, but I wanted to evaluate how many codebases are actually using it. Luckily, very few, but this is one of them. :) It seems to me that all the usages here can be ported directly to Q_DISABLE_COPY_MOVE, and that could even be scripted and quickly done.

Note: this deprecation, if anything, will appear in Qt 6.2 *minimum*, so there's absolutely no urgency, this is just a heads-up.

Thanks.

**Comment by buschmann23** [comment]
Closed in ea975a6
